#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct  1 16:58:47 2023

@author: lucina-may
"""

BETTER_TAX = {
    "Viridiplantae": "Viridiplantae",
    "Bacteria <bacteria>": "Bacteria",
    "Pseudomonadota": "Bacteria",
    "Eukaryota": "Eukaryota",
    "Magnoliopsida": "Viridiplantae",
    "cellular organisms": "Cellular organisms",
    "Bryophyta": "Viridiplantae",
    "Pimpinella": "Viridiplantae",
    "Brassicaceae": "Viridiplantae",
    "Equisetum": "Viridiplantae",
    "Spermatophyta": "Viridiplantae",
    "Fabaceae": "Viridiplantae",
    "Tracheophyta": "Viridiplantae",
    "Fungi": "Fungi",
    "Mammalia": "Metazoa",
    "Gunneridae": "Viridiplantae",
    "Capsicum": "Viridiplantae",
    "asterids": "Viridiplantae",
    "Solanaceae": "Viridiplantae",
    "Rutaceae": "Viridiplantae",
    "Amaryllidaceae": "Viridiplantae",
    "Ephedra": "Viridiplantae",
    "Ranunculales": "Viridiplantae",
    "Papaveraceae": "Viridiplantae",
    "Berberidaceae": "Viridiplantae",
    "Caryophyllaceae": "Viridiplantae",
    "Homo": "Metazoa",
    "Archaea": "Archaea",
    "Methanococci": "Archaea",
    "Penicillium": "Fungi",
    "Lathyrus": "Viridiplantae",
    "Embryophyta": "Viridiplantae",
    "Clavicipitaceae": "Fungi",
    "Streptomyces": "Bacteria",
    "Solanum": "Viridiplantae",
    "Cyanobacteriota": "Bacteria",
    "Bacilli": "Bacteria",
    "Amygdaloideae": "Viridiplantae",
    "Poaceae": "Viridiplantae",
    "Lamiaceae": "Viridiplantae",
    "Vertebrata <vertebrates>": "Metazoa",
    "Allioideae": "Viridiplantae",
    "Caryophyllales": "Viridiplantae",
    "Drosophila <flies,genus>": "Metazoa",
    "Streptomycetales": "Bacteria",
    "Chlorophyta": "Viridiplantae",
    "Euphyllophyta": "Viridiplantae",
    "Insecta": "Metazoa",
    "Lepidoptera": "Metazoa",
    "Pinidae": "Viridiplantae",
    "Gossypium": "Viridiplantae",
    "Santalum": "Viridiplantae",
    "Shewanellaceae": "Bacteria",
    "Thermoprotei": "Archaea",
    "Chromatiaceae": "Bacteria",
    "Iridaceae": "Viridiplantae",
    "eudicotyledons": "Viridiplantae",
    "lamiids": "Viridiplantae",
    "Myxococcales": "Bacteria",
    "Actinomycetota": "Bacteria",
    "Shewanella": "Bacteria",
    "Cyperus": "Viridiplantae",
    "Cannabaceae": "Viridiplantae",
    "Cannabis": "Viridiplantae",
    "Hypericum": "Viridiplantae",
    "Metazoa": "Metazoa",
    "Sphingomonadales": "Bacteria",
    "Haptophyta": "Viridiplantae",
    "Actinomycetes": "Bacteria",
    "Apocynaceae": "Viridiplantae",
    "Protostomia": "Metazoa",
    "Enterobacterales": "Bacteria",
    "Erythroxylaceae": "Viridiplantae",
    "Halobacteria": "Archaea",
    "Escherichia coli": "Bacteria",
    "Streptomycetaceae": "Bacteria",
    "Bacillota": "Bacteria",
    "Coffea": "Viridiplantae",
    "Opisthokonta": "Opisthokonta",  # animal/fung
    "Boraginaceae": "Viridiplantae",
    "Sorghum": "Viridiplantae",
    "Mesangiospermae": "Viridiplantae",
    "Rosaceae": "Viridiplantae",
    "Marchantiophyta": "Viridiplantae",
    "Rhodophyta": "Viridiplantae",
    "Brassicales": "Viridiplantae",
    "Bacteroidales": "Bacteria",
    "Helicobacter pylori": "Bacteria",
    "Corynebacteriales": "Bacteria",
    "Ascomycota": "Fungi",
    "Haemodoraceae": "Viridiplantae",
    "Lecanorineae": "Fungi",
    "Lactobacillales": "Bacteria",
    "Theaceae": "Viridiplantae",
    "Rubiaceae": "Viridiplantae",
    "Rhizobiaceae": "Bacteria",
    "Methanobacteria": "Archaea",
    "Populus": "Viridiplantae",
    "Porphyromonas gingivalis": "Bacteria",
    "Lampyridae": "Metazoa",
    "Gammaproteobacteria": "Bacteria",
    "Mycobacteriaceae": "Bacteria",
    "Enterobacteriaceae": "Bacteria",
    "Arthropoda": "Metazoa",
    "Thermococci": "Archaea",
    "Chlamydia": "Bacteria",
    "Mimoseae": "Viridiplantae",
    "Bacillariophyta": "Viridiplantae",
    "Apiales": "Viridiplantae",
    "Avena": "Viridiplantae",
}
